version: '3'
services:
  db:
    image: postgres
    container_name: fieldlab_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Robotti123
      POSTGRES_DB: test_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init/postgres.conf:/etc/postgresql/postgresql.conf
      - ./init:/docker-entrypoint-initdb.d/
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always

  adminer:
    image: adminer
    container_name: fieldlab_adminer
    restart: always
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana:latest
    container_name: fieldlab_grafana
    ports:
      - 3000:3000
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana
  
  nodeapi:
    build: ../node-back/
    container_name: fieldlab_nodeapi
    ports:
      - 9080:8080

  react-ui:
    build: ../react-front/
    container_name: development_ui
    ports:
      - 3100:3000

volumes:
  pgdata:
    driver: local
  grafana-storage:
